### ISSUE TITLE
Plan out file structure

### ISSUE THREAD

**Issue by ghost** [MysteriousBagel/mood.ly#1]

**Comment by CodeRISHI** [comment]
If everyone is okay with using Yeoman for scaffolding, we can use that and set up our file structure and dependencies.

Here is a link in case you guys want to read more about it: http://yeoman.io/

**Comment by CodeRISHI** [comment]
No go on Yeoman (for now). Created a file structure from scratch. Basic structure set up. Closing this issue - will revisit if any issue(s).
